apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-example
  name: nginx-example-deployment
spec:
  selector:
    matchLabels:
      app: nginx-example
  template:
    metadata:
      labels:
        app: nginx-example
    spec:
      containers:
      - env:
        image: nginx:latest
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 30
          timeoutSeconds: 60
        name: nginx-example
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 60
